"""added column to recipe table

Revision ID: 603703f6c809
Revises: f707826e7257
Create Date: 2022-01-09 21:23:50.903271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603703f6c809'
down_revision = 'f707826e7257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('need_for_shaker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'need_for_shaker')
    # ### end Alembic commands ###
