"""Recipe and Alcohol tables

Revision ID: f707826e7257
Revises: 
Create Date: 2022-01-09 07:59:17.076120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f707826e7257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcohol_name'), 'alcohol', ['name'], unique=True)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ingredients', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients'), 'recipe', ['ingredients'], unique=False)
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_ingredients'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_alcohol_name'), table_name='alcohol')
    op.drop_table('alcohol')
    # ### end Alembic commands ###
